# AllCops:
  # TargetRubyVersion: 2.5

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/MethodLength:
  Max: 16

Style/Documentation:
  Enabled: false

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

# Style/FrozenStringLiteralComment:
  # EnforcedStyle: never

# Enables Russian comments for difficult logic
Style/AsciiComments:
  Enabled: false