#!/bin/bash

# if [ -n "$1" ] # checks if any arg passed
# then
   # branch=$1
# else
   # branch='master'
# fi

git fetch $REMOTE
git checkout $BRANCH
git branch --set-upstream-to=$REMOTE/$BRANCH

git pull
