#!/bin/bash

# if [ -n "$1" ] # checks if any arg passed
# then
   # branch=$1
# else
   # branch='master'
# fi

source $DESKTOP_FOLDER/script.sh
git fetch $BOT_REMOTE
git checkout $BOT_BRANCH
git branch --set-upstream-to=$BOT_REMOTE/$BOT_BRANCH

git pull
