# Переменные, заканчивающиеся на _range состоят из двух значений: верхняя и нижняя
# границы диапазона, в пределах которого выбирается случайное значение
#
# Переменные, заканчивающиеся на _sample используют случайное значение из
# списка
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Новое !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# Переменные начинающиеся на rival_, target_, search_, link_ будут использовать
# значения без этого префикса как дефолтные к примеру
# `target_scroll_speed: 2, scroll_speed: 4` будет скроллить целевые сайты со скоростью 2
# а все остальные - поисковую страницу, не целевые, ссылки со скоростью 4


# Режим работы программы:
# 1 - Обычный
# 2 - Облегченный: клики +  1) доп целевые и второстепенные целевые,
#                           2) игнор целевых ниже заданного числа,
#                           3) скорость прокрутки страницы поиска,
#                           4) отложить при достижения цели, либо при отсутствии,
#                           5) диапазон пауз между объявлениями и между вводом запросов
#                           6) Пауза при возникновении ошибки
# 3 - Ручной режим
mode: 1

# нецелевой = вражеский
# дополнительные ссылки для нецелевого - переходы с ворожнечого сайта куда-то
# задержка сбора ссылок - время ожидания смены ссылки после нажатия на нее в поисковике
# 

################################################################################
# Запросы
#

# Поисковые запросы
queries:
  # - что-то/podskajem/5
  - установка лампы
  - вызов електрика ~ -skip_target # Определена опция запроса skip_target
# Опции запросов (если будут еще опции...) прописываются как в примере наверху после ` ~ `
# `-skip_target` - псевдо будет рассчитан с учетом нахождения целевого на странице,
#                  но целевой будет пропущен.

# Дополнительные ссылки для нецелевого
additional_visits:
  - http://google.com
  - http://onhour.ru


# Диапазон паузы между поисковыми запросами (с)
search_delay_range:
  - 2.0
  - 3

# Пауза между переходами по ссылкам
links_delay_range:
  - 2.0
  - 3

# Задержка сбора ссылок
links_harvest_delay_range:
  - 1.0
  - 3

# Игнорировать целевые сайты ниже следующей позиции
results_limit: 12

# Диапазон количества обрабатываемых результатов на один поисковой запрос
results_count_range:
  - 10
  - 10

# Осуществлять переходы только с уникальным ip
unique_visit_ip?: false

# Пауза между проверками ip (межу запросами) (c)
check_ip_delay: 20

# Пауза между запросами при возникновении ошибки (с)
error_delay: 10

# Отложить обработку, если:
query_skip_on_position_by_limit: 0 # позиции целевых сайтов не ниже значения
query_skip_on_presence?: false # целевых сайтов нет в выдаче
query_skip_on_limit: 20 # отложить из-за отсутствия прогресса
query_skip_on_non_pseudos_below_pseudo?: true # сайты к пропуску ниже доп. целевого

# Отложить после обработки запроса, если целевые наверху
query_skip_after_perform?: true

# Отложить обработку на время (минут)
query_skip_interval: 2
query_skip_on_presence_interval: 1 # нет на странице
query_skip_on_limit_interval: 2 # из-за отсутствия прогресса

# Процент использования мобильных user-agent
# 0 - только компы, 100 - только мобилы
mobile_chance: 0

# Использовать user-agent-ы с сайта
use_real_ua?: true


################################################################################
# Результаты

# Целевые сайты. Первый - основной, остальные - второстепенные
# Домен может быть обработан единожды за поисковый запрос
# при повторе домена последующие игнорируются
target_patterns:
  - lideruslug.ru

# Нецелевые сайты(вражеские), если не задано, то все кроме игнорируемых/целевых.
rival_patterns:
  - onhour

# Игнорируемые сайты
skip_site_patterns:
  # - fer

# Дополнительные целевые сайты (обрабатывается как целевой)
pseudo_targets: # если есть целевой сайт на странице
  - 1
  - 3
sole_pseudo_targets: # если целевого сайта нет на странице
  - 2
  - 5

# Процент пропуска 
target_skip_chance: 25 # целевого
pseudo_skip_chance: 0 # доп целевого
rival_skip_chance: 0 # нецелевых сайтов.

# Глубинные посещения для целевого сайта
# Диапазон глубины просмотра (количество переходов по ссылкам)
explore_deepness_sample:
  - 0
# Пауза между глубинными переходами (с)
explore_delay_range:
  - 1.0
  - 4

# Время ожидания после клика по ссылке в поисковике
rival_pre_delay_range: # для нецелевых сайтов (c)
  - 0.1
  - 0.3
target_pre_delay: 1 # для целевых сайтов
pre_delay: 1 # дефолтное

# Минимальное время посещения (c)
rival_min_visit_range:  # нецелевого сайта
  - 2
  - 2
target_min_visit_range: # целевого сайта
  - 2
  - 2

# Диапазон паузы между объявлениями (с)
result_delay_range:
  - 1
  - 1

# Для целевых: кликать по последнему элементу пути
target_last_path_link?: true
# Для нецелевых: кликать по последнему элементу пути
rival_last_path_link?: true


################################################################################
# ДЕЙСТВИЯ
# все значения определяющие действия поддерживают приставки target_, rival_, search_

## -------- СКРОЛЛ(ПРОКРУТКА) + ДВИЖЕНИЯ МЫШКОЙ К ССЫЛКЕ
# Включение системного скролла и движения мышкой к элементу(ссылке)
target_system_scroll: true # для целевых
system_scroll: false # для остальных(поисковая страница, не целевые)

# скорость системного движения мышкой.
mouse_move_range:
  - 3
  - 5
# задержка между системными движениями мышки.
mouse_move_delay_range:
  - 0.008
  - 0.012

# Диапазон высоты прокрутки(%):
scroll_height: 0 # дефолтное
target_scroll_height_range: # теперь настраивается и для целевых
  - 60
  - 80

# Скорость прокрутки (по умолчанию 4)
rival_scroll_speed: 5 # для нецелевых
target_scroll_speed: 3 # для целевого
search_scroll_speed: 4 # на странице поиска

# Диапазон задержки прокрутки(c). Желательно не ниже 0.1, может начать неточно работать
# из-за задержки обновления получаемой из браузера информации.
rival_scroll_delay_range: # для нецелевыx
  - 0.1
  - 0.2
scroll_delay: 1 # для всего остального:

# Множитель величины прокрутки:
# Если не задать множитель, а только границу, то будет скроллить относительно разницы
# границы и реальной высоты страницы - (высота страницы / threashold) * скорость прокрутки
scroll_multiplier: 2.5
# если сайт длиннее (px):
scroll_threshold: 1200

## -------- РАНДОМНЫЕ ДВИЖЕНИЯ МЫШКОЙ
# Выполняется одновременно с скроллом(прокруткой) выбирает вектор движения
# И заданное кол-во итераций движется в том направлении
# Как только закончится скролл, закончатся и рандомные движения

# Включение рандомных движений мышкой во время скролла
target_random_mouse_move: true # для целевых
random_mouse_move: false # для остальных

# "скорость" рандомных движений складывается из
# Расстояния проходимого мышкой за одну итерацию
random_move_by_x_range:
  - -5
  - 5
random_move_by_y_range:
  - -5
  - 5
# Кол-во итераций рандомного движения мышкой
random_moving_iterations_range:
  - 1
  - 10
# Ожидание внутри итерации(нужно для сглаживания движения)
random_moving_delay: 0.02
# Ожидание между итерациями

## ----------- КЛИКИ
# Включение системных кликов по объектам(ссылкам)
target_system_click: true


################################################################################
# Другое
#

# Не переходить по ссылкам
ignore_patterns:
  - реклама
  - yandex
  - яндекс
  - mail.ru
  - youtube
  - wikipedia
  - турбо

# Использовать прокси? (true = да, false = нет)
# use_proxy?: false

# Задержка сетевого соединения (ms)
throttling_latency: 0

# Пропускная способность (0 - 500)
throttling_trhoughput: 500

# Прокси серверы
# proxy_sample:
#   - 31.44.88.1:49503
#   - 83.69.180.83:42195
#   - 94.124.193.244:36288
#   - 146.66.14.50:32092
#   - 185.9.86.186:39345

# Идентификаторы блоков с внутренними ссылками
nav_classes:
  - service-links
  - category-sidebar

# Поиск доступен только в яндексе пока
# engine: yandex.ru
