#
# Поисковые запросы
#
queries:
  - как чистить зубы
  - человек колесо

#
# Продвигаемый домен
#
target: timeboil

#
# Количество обрабатываемых результатов на один поисковой запрос
#
results_count: 2

#
# Не переходить по ссылкам
#
ignore:
  - реклама
  - yandex
  - яндекс
  - mail.ru
  - youtube



nav_classes:
  - sub

engine: yandex.ru
