# Переменные, заканчивающиеся на _range состоят из двух значений: верхняя и нижняя
# границы диапазона, в пределах которого выбирается случайное значение
#
# Переменные, заканчивающиеся на _sample используют случайное значение из
# списка


# Режим работы программы:
# 1 - Обычный
# 2 - Облегченный: клики +  1) доп целевые и второстепенные целевые,
#                           2) игнор целевых ниже заданного числа,
#                           3) скорость прокрутки страницы поиска,
#                           4) отложить при достижения цели, либо при отсутствии,
#                           5) диапазон пауз между объявлениями и между вводом запросов
#                           6) Пауза при возникновении ошибки
# 3 - Ручной режим
mode: 1


################################################################################
# Запросы
#

# Поисковые запросы
queries:
  # - что-то/podskajem/5
  - установка лампы

# Дополнительные ссылки для нецелевого
additional_visits:
  - http://google.com
  - http://onhour.ru


# Диапазон паузы между поисковыми запросами (с)
query_delay_range:
  - 2.0
  - 3

# Пауза между переходами по ссылкам
links_delay_range:
  - 2.0
  - 3

# Задержка сбора ссылок
links_harvest_delay_range:
  - 1.0
  - 3

# Игнорировать целевые сайты ниже следующей позиции
results_limit: 12

# Диапазон количества обрабатываемых результатов на один поисковой запрос
results_count_range:
  - 10
  - 10

# Осуществлять переходы только с уникальным ip
unique_visit_ip?: false

# Пауза между проверками ip (межу запросами) (c)
check_ip_delay: 20

# Пауза между запросами при возникновении ошибки (с)
error_delay: 10

# Отложить обработку, если:
query_skip_on_position_by_limit: 0 # позиции целевых сайтов не ниже значения
query_skip_on_presence?: false # целевых сайтов нет в выдаче
query_skip_on_limit: 20 # отложить из-за отсутствия прогресса
query_skip_on_non_pseudos_below_pseudo?: true # сайты к пропуску ниже доп. целевого

# Отложить после обработки запроса, если целевые наверху
query_skip_after_perform?: true

# Отложить обработку на время (минут)
query_skip_interval: 2
query_skip_on_limit_interval: 2 # из-за отсутствия прогресса

# Процент использования мобильных user-agent
# 0 - только компы, 100 - только мобилы
mobile_chance: 0

# Использовать user-agent-ы с сайта
use_real_ua?: true

# Допустимые периоды ожидания загрузки при вводе ссылки в строку(переход на яндекс)
# open_timeout: 20 # 
page_load_timeout: 30 # период ожидания загрузки страницы


################################################################################
# Результаты
#

# Целевые сайты. Первый - основной, остальные - второстепенные
target_patterns:
  - lideruslug.ru

# Процент пропуска неосновного и доп целевого
skip_target_chance: 0

# Нецелевые сайты
non_target_patterns:
  - onhour

# Не могут быть целевыми
skip_site_patterns:
  # - fer

# Процент пропуска нецелевых сайтов
skip_chance: 0

# Дополнительные целевые сайты
pseudo_targets: # если есть целевой сайт на странице
  - 1
  - 3
sole_pseudo_targets: # если целевого сайта нет на странице
  - 2
  - 5


# Диапазон глубины просмотра целевого сайта (количество переходов по ссылкам)
explore_deepness_sample:
  - 0

# Дополнительное время клика для нецелевых сайтов (c)
pre_delay_non_target_range:
  - 0.2
  - 0.3
pre_delay_target: 0 # для целевых сайтов
pre_delay_link: 1 # для ссылок

# Минимальное время посещения (c)
min_visit_non_target_range:  # нецелевого сайта
  - 2
  - 2
min_visit_target_range:      # целевого сайта
  - 2
  - 2

# Диапазон паузы между объявлениями (с)
result_delay_range:
  - 1
  - 1

# Пауза между переходами внутри сайта (с)
explore_delay_range:
  - 1.0
  - 4

# Диапазон высоты прокрутки нецелевых сайтов (%)
scroll_height_non_target_range:
  - 0
  - 0

# Диапазон высоты прокрутки ссылок (%)
scroll_height_link_range:
  - 0
  - 0

# Скорость прокрутки для нецелевых (по умолчанию 4)
scroll_speed: 4
# для целевого
scroll_speed_target: 1

# Диапазон задержки прокрутки для нецелевых (с)
scroll_delay_range:
  - 0.2
  - 3.8
# для целевых
scroll_delay_target_range:
  - 0.1
  - 4.1

# Диапазон величины прокрутки за раз для нецелевых (px)
scroll_amount_range:
  - 20
  - 180
# для целевых
scroll_amount_target_range:
  - 20
  - 180

# Множитель величины прокрутки:
scroll_multiplier: 2.5
# если сайт длиннее (px):
scroll_threshold: 1800

# Для целевых: кликать по последнему элементу пути
last_path_link_target?: true
# Для нецелевых: кликать по последнему элементу пути
last_path_link_rival?: true




################################################################################
# Другое
#

# Не переходить по ссылкам
ignore_patterns:
  - реклама
  - yandex
  - яндекс
  - mail.ru
  - youtube
  - wikipedia
  - турбо

# Использовать прокси? (true = да, false = нет)
use_proxy?: false

# Задержка сетевого соединения (ms)
throttling_latency: 0

# Пропускная способность (0 - 500)
throttling_trhoughput: 500

# Прокси серверы
proxy_sample:
  - 31.44.88.1:49503
  - 83.69.180.83:42195
  - 94.124.193.244:36288
  - 146.66.14.50:32092
  - 185.9.86.186:39345

# Идентификаторы блоков с внутренними ссылками
nav_classes:
  - service-links
  - category-sidebar

# Поиск доступен только в яндексе пока
engine: yandex.ru
