#!/bin/bash

if [ -z $Developer ]
then
   if [ -n "$1" ] # checks if any arg passed
   then
       branch=$1
   else
       branch='master'
   fi

   git fetch origin
   git checkout $branch
   git pull origin $branch
fi

ruby start.rb
